"""fie_common — shared configuration, errors, and resilience primitives.

Phase 1 constraint: this package (and every other ``packages/*`` package)
contains infrastructure only. No financial domain logic lives here.
"""

from fie_common.config import (
    CoreSettings,
    Environment,
    FIEBaseSettings,
    LogLevel,
    SecretStr,
    require_production_secret,
    secret_value,
)
from fie_common.errors import (
    AIProviderError,
    AIProviderRateLimitError,
    AIProviderRefusalError,
    AIProviderResponseError,
    AIProviderTimeoutError,
    AuthenticationError,
    AuthorizationError,
    CircuitOpenError,
    ConfigurationError,
    ConflictError,
    DatabaseError,
    EventBusError,
    ExternalServiceError,
    FIEError,
    NotFoundError,
    OperationTimeoutError,
    RateLimitError,
    ValidationError,
)
from fie_common.resilience import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitState,
    ResiliencePolicy,
    RetryPolicy,
    default_retryable,
    retry_async,
    with_timeout,
)
from fie_common.utils import (
    REDACTED,
    SENSITIVE_KEYS,
    chunked,
    coalesce,
    content_hash,
    new_id,
    redact_mapping,
    redact_secret,
    stable_json,
    utc_now,
)

__version__ = "0.1.0"

__all__ = [
    "REDACTED",
    "SENSITIVE_KEYS",
    "AIProviderError",
    "AIProviderRateLimitError",
    "AIProviderRefusalError",
    "AIProviderResponseError",
    "AIProviderTimeoutError",
    "AuthenticationError",
    "AuthorizationError",
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitOpenError",
    "CircuitState",
    "ConfigurationError",
    "ConflictError",
    "CoreSettings",
    "DatabaseError",
    "Environment",
    "EventBusError",
    "ExternalServiceError",
    "FIEBaseSettings",
    "FIEError",
    "LogLevel",
    "NotFoundError",
    "OperationTimeoutError",
    "RateLimitError",
    "ResiliencePolicy",
    "RetryPolicy",
    "SecretStr",
    "ValidationError",
    "__version__",
    "chunked",
    "coalesce",
    "content_hash",
    "default_retryable",
    "new_id",
    "redact_mapping",
    "redact_secret",
    "require_production_secret",
    "retry_async",
    "secret_value",
    "stable_json",
    "utc_now",
    "with_timeout",
]
